version: 2

updates:
  - package-ecosystem: cargo
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
    groups:
      wgpu:
        patterns: ["wgpu*", "naga"]
      serde:
        patterns: ["serde*"]

  - package-ecosystem: github-actions
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
